### ISSUE TITLE
Build for multiple targets

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/easy-speech#107]
EasySpeech should be available for multiple targets (umd, amd, esm etc.).

**Comment by jankapunkt** [comment]
@andre-dietrich I created a new PR where the package is now build for multiple targets and also with best possible browser support for demo. Care to take a look at it? --> #114

**Comment by andre-dietrich** [comment]
Ok, I will check this with my Nokia-Phone and get back to you ;-)
