### ISSUE TITLE
Provide a pause() and resume() workaraound for Android Browsers

### ISSUE THREAD

**Issue by hudsantos** [jankapunkt/easy-speech#108]
Hi @jankapunkt thanks for your great work here in this project.

This issue i'm filling up here is more about **speechSynthesis** itself, not the EasySpeech library. Just would like to know if you or anyone have any clue on what can be done in this particular case.

Problem is that the following snippet works well on Desktop Chrome but not on Mobile Chrome (Android):

```javascript
var to_speak = "The text we want browser to pronounce, long enough to be able to pause it.."
var utterance = new SpeechSynthesisUtterance(to_speak)
utterance.lang = 'en-US'
window.speechSynthesis.speak(utterance)

// Then pause and resume:

window.speechSynthesis.pause()
window.speechSynthesis.resume()
```

According to this comment: https://github.com/jankapunkt/easy-speech/blob/045f6aa4e4c0eea5cd2088e8c8c569968d0ef702/index.js#L797

..it looks like this is a known issue.

But even using `window.speechSynthesis.cancel()` I could not workaround that.
I'm pretty convinced that being able to workaround that, it will be possible to invoke pause and resume using `EasySpeech.pause()` AND `EasySpeech.resume()` abstractions.

**Comment by jankapunkt** [comment]
This is problematic on Android overall and since `charIndex` (as part of SpeechSynthesisEvent) is not available on all Android Browsers, otherwise we could simply stop, detect the `charIndex` and resume by playing a new utterance, beginning from the last charIndex.

I will check for more potential workarounds.

**Comment by hudsantos** [comment]
As additional info, here goes a few behavior I could collect, still focusing SpeechSynthesis object:

**ANDROID Chrome:**

While speaking: `SpeechSynthesis {pending: false, speaking: true, paused: false, onvoiceschanged: null}`

After pause: `SpeechSynthesis {pending: false, speaking: true, paused: false, onvoiceschanged: null}`

**DESKTOP Chrome:**

While speaking: `SpeechSynthesis {pending: false, speaking: true, paused: false, onvoiceschanged: null}`

After pause: `SpeechSynthesis {pending: false, speaking: true, paused: false, onvoiceschanged: null}`

**BOTH AFTER NORMAL SPEAK ENDS:**

`SpeechSynthesis {pending: false, speaking: false, paused: false, onvoiceschanged: null}`

**Comment by hudsantos** [comment]
Well fortunately those APIs (speechSynthesis / SpeechSynthesisUtterance)  exists but unfortunately are still very experimental over the last decade.. 😭

The `.onpause` and `.onresume` doesn't work in desktop Google Chrome latest version either, although it's documented by mozilla https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisEvent/charIndex

A panorama potentially influenced by this: cloud dot google dot com slash text-to-speech slash pricing

**Comment by jankapunkt** [comment]
Closing this for now as this can't be fixed unless Android browsers provide some functionality to detect the last play position and resume at this positon.
