### ISSUE TITLE
Playback speed (normal rate=1.0) faster on mac m1 that other laptops

### ISSUE THREAD

**Issue by rickghome** [jankapunkt/easy-speech#116]
Something we've noticed while testing EasySpeech is that playback with same content on M1 mac plays back at a faster rate than the same exact test on other laptops (given the exact same TTS settings). Anyone else seen this?

**Comment by jankapunkt** [comment]
@rickghome which browser/version did you use for the test? Maybe I can replicate this with a teammate, who owns a M1, while I still own an Intel-based Mac.

**Comment by rickghome** [comment]
Tried this on both chrome and safari, and the results were the same.

**Comment by shubham-mathur-mdl** [comment]
it happens randomly on i9 Macbook pro also. Sometime it works perfectly, sometime I have to open the page in incognito.

**Comment by jankapunkt** [comment]
I still wonder if this is related rather to the safari implementation or on a OS level. If we get a clue on how we distinctively know to what this is related in a reproducible way then I can provide a fix.

I have unfortunately an older Mac from 2018 but I could try to check if this is Safari related or not.

@rickghome @shubham-mathur-mdl what are your MacOs / Safari versions?

**Comment by shubham-mathur-mdl** [comment]
I am using MacBook Pro 16" 2019 MacOS Ventura 13.4. I am using chrome not Safari.

**Comment by shib-heystartup** [comment]
I'm seeing the same issue.

Both Chrome and Firefox on my M1 MacBook playback at a faster rate than Safari. The rate Safari plays back at is what I would expect given the options set (both rate and pitch are set at 1).

Computer specs:

MacBook Pro 14" 2021
Apple M1 Pro Chip
Ventura 13.4

**Comment by jankapunkt** [comment]
At what configuration (rate, pitch, voice(s)) does it sound "normal"?

**Comment by shib-heystartup** [comment]
Both Chrome and FF sound "normal" (they match Safari, by ear at least) with the following: 

Rate: 0.9
Pitch: 1

Voice I'm using is Karen, if that helps. I've put their index's below 'cause they vary by browser.

Safari: EasySpeech.voices()[15];
Chrome/FF: EasySpeech.voices()[66];

I can get a sound recording if you'd like as well :)

**Comment by jankapunkt** [comment]
@shib-heystartup thank you for the detailed info. One more question - can you please try using the `say` command on your Mac M1 Terminal using the Karen voice as parameter but no arguments for pitch and rate. Do these system "defaults" also sound correct or rather slow, too?

**Comment by shib-heystartup** [comment]
OK! So, the Terminal `say` command with the Karen voice and no other arguments sounds correct! It sounds exactly the same as the output I get when I run it on Safari.

I'm using your demo site (https://jankapunkt.github.io/easy-speech/) to test it on browser by the way so there's none of my code messing it up. :)

**Comment by rickghome** [comment]
I happen to be running on an M2 Mac if that matters. One of my developers is on an intel MacBook Air, and gets the same results. There is no doubt about the fact that playback speed are different.

**Comment by jankapunkt** [comment]
@shib-heystartup @rickghome  I just have replicated this issue with a non-M1 Macbook, too.

Hardware: MacBook Air 13"; 2018 with Intel Core i5
OS: MacOS Ventura 13.4

Safarai: 16.5
Firefox: 114.0.2
Chrome: 115.05790.170
Language: en
Voice: Karen

It's exactly the behaviour, as described by @shib-heystartup 

@rickghome the only thing that wonders me now is your report, that it was on correct speed on Chrome. Did you by any chance used a google voice there? I found, that the google voice provide the most coherent experience in Chrome on any device/os combination, so I would avoid to use them for testing this issue and focus on the Apple system voices (Karen, Siri, Eddy, Daniel, Shelly, Sandy etc.) 

@shib-heystartup / @rick Also note, that there are multiple versions of the same voice sometimes, for example I have many voices as GB and US version as I just installed available now for testing :-)

I really like to narrow this issue down so we can find the best solution or workaround for this.

**Comment by shib-heystartup** [comment]
@jankapunkt Glad you were able to replicate! 

I noticed there were multiple voice versions! I've also got multiples of US/UK voices on my Macbook. I needed an AU voice though and luckily Karen's the only one! I can't see a multiple for her. 

I did just check and it's also happening with Daniel (GB) and Eddy (GB) so I suspect it's not a singular voice issue. It's weirdly *very* noticeable with the Eddy (GB) voice!

**Comment by jankapunkt** [comment]
> It's weirdly very noticeable with the Eddy (GB) voice!

I actually found this very revealing analysis: https://apple.stackexchange.com/questions/96808/what-is-the-default-speaking-rate-for-the-speech-synthesis-program

So my assumption here is, that Safari/WebKit internally has knowledge about this and makes rate=1 relative to the several voices defaults while FF/Chrome don't "know" this fact and simply send a global default rate. I will investigate further on this and check the Browser Engine implementations if they reveal something.

**Comment by jankapunkt** [comment]
Please read the comment in the Chromium code: https://github.com/chromium/chromium/blob/8f866f48d0fbf1a7741c1194b30b19c05d16ed7d/content/browser/speech/tts_mac.mm#L222
