### ISSUE TITLE
Speak when voices won't load but speech synth and utterance are available (Brave shields up issue)

### ISSUE THREAD

**Issue by RandyLoeb** [jankapunkt/easy-speech#49]
When brave shields are up, the list of voices is never seen.
Nonetheless, an utterance can speak. 
.speak may need some option like "do it anyway!" even when the voices array is empty.

**Comment by jankapunkt** [comment]
Hey @RandyLoeb can you add the init status and the log from https://jankapunkt.github.io/easy-speech/ since I don't have brave installed. But with the output I should be able to tweak this a bit to get make it possible to speak even without a loaded list.

**Comment by RandyLoeb** [comment]
Sorry for delay, I will try to grab and test the fix, is it part of npm package or do I need to get from github?
I have been wrestling with some other safari-on-ipad speak problems that have me quite baffled.

**Comment by RandyLoeb** [comment]
Oh sorry, no the safari issue has nothing to do with your code. But if you're volunteering to be another set of eyes.... ;-)
