### ISSUE TITLE
DEMO Website - slider's don't apply

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/easy-speech#70]
On the DEMO users can apply sliders to change rate, pitch and volume. It seems they don't work correctly.
Demo code is in the `docs` folder.

**Comment by RachitGarg-12** [comment]
@jankapunkt i would like to work on this issue.

**Comment by jankapunkt** [comment]
Hi @RachitGarg-12 thank you, please open a new pull request. Use draft-pull request if you want to let me know that your work is not finished, yet. I will review, once you convert from draft to normal pull request and assign me as reviewer.

**Important:** Please also consider the [contribution guidelines](https://github.com/jankapunkt/easy-speech/blob/master/CONTRIBUTING.md). Since this would affect no code of the package, there is no need to update the changelog.

**Comment by jankapunkt** [comment]
Fixed with https://github.com/jankapunkt/easy-speech/releases/tag/v2.1.0
