### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by Gopal2021025** [jankapunkt/easy-speech#71]
Add header to your site -:
The header includes the name of the site like the one's given below .
![navbar](https://user-images.githubusercontent.com/96721011/196602776-3123b0d2-7a27-42d3-aa2d-269a23e301bf.png)

**Comment by jankapunkt** [comment]
Thank you @Gopal2021025 for contributing to this project. Can you please add a few more details, so others (especially people new to development) know exactly what is meant.

**Comment by Gopal2021025** [comment]
@jankapunkt kindly check it now

**Comment by jankapunkt** [comment]
@Gopal2021025 so you intend to add a responsive Bootstrap Navbar, right? Please make sure the current menu of the page (API docs, GitHub link)  is included correctly there.

**Comment by Gopal2021025** [comment]
@jankapunkt yes I want to make a responsive Bootstrap navbar . I will include link to API and github docs as well . Just a question do I have to include code style , test suite as well ?

**Comment by jankapunkt** [comment]
@Gopal2021025 the CI will run tests and lint anyways but yes, please consider to run a linter on the website code as well. Once the code is updated you need to build it using the npm script. Please don't include changes to the package code, though. There is also no need to update the changelog for this one.

**Comment by Gopal2021025** [comment]
@jankapunkt  Can you assign me this issue ?

**Comment by jankapunkt** [comment]
@Gopal2021025 no worries, just open a new pull request or use draft pull request to indicate early stage work. I will assign you, once the PR is there.

**Comment by Gopal2021025** [comment]
@jankapunkt I have made a PR kindly check
