### ISSUE TITLE
Does not work on KaiOS

### ISSUE THREAD

**Issue by andre-dietrich** [jankapunkt/easy-speech#83]
Hi, this is a really, really, really great project. We use it now in LiaScript to generate the default TTS output for courses. I tested it on KaiOS, which seems to have a TTS-support, with the standard API and good voices (the demo from MDN works fine). However, easy-speech does not support this OS/Browser.

Maybe it would be possible to add another unknown - system, next to android, safari, etc. that allows to access the API, when the browser supports TTS and also offers some voices?

I know, why supporting edge-case feature-phones? But, they have a larger market share in India than IPhone ...

https://www.kaiostech.com/developers/

It would be great to add this support to easy-speech ...

Kind regards ...

**Comment by jankapunkt** [comment]
Hi @andre-dietrich could you please help me with debugging and use one of the KaiOS devices and go to the demo page using the KaiOS browser:

https://jankapunkt.github.io/easy-speech/

Then please copy the output from the tabs `Init status` and `Debug log`. A screenshot image is also fine. This should already help a lot to identitfy what's causing trouble.

**Comment by andre-dietrich** [comment]
Hi, sorry for the late response ... I tried it now on multiple ways. I used the simulator, with a newer version of KaiOS, where your lib works like charm. On my testing device however, I could not run it, after setting up the debug-environment, it seems that the script was not executed at all, event transpiling it with babel was not successful. I will go step by step through it, to figure out, what peace of JS might cause this behavior and write you an update ... thanks again, for this nice little lib ;-)

**Comment by andre-dietrich** [comment]
It took some time, but now it runs on my Nokia with KaiOS 2.5, which uses an older version of Firefox (49). However, the docs folder will not run directly, it requires an additional transpilation to es5. Previously I tried to manually replace the spread operator `...` and the question mark `?`. But this did not work for `async` and `await` in `docs/main.js`. Maybe the demo site could be transpiled automatically to reach a wider set of browsers with TTS support.

**Comment by jankapunkt** [comment]
Thank you! 
I simply forgot to add this step when building the docs. Of course, we should be ES5 compliant. Let me check, if I can add this easily to the build step.

**Comment by jankapunkt** [comment]
Fixed in release [1.2.1](https://github.com/jankapunkt/easy-speech/releases/tag/v1.2.1)
